# Generated by Django 3.2.5 on 2021-08-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Attendants_in_session', to='core.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='attendants',
            field=models.ManyToManyField(blank=True, related_name='session_name', to='core.Attendant'),
        ),
    ]
