# Generated by Django 3.2.5 on 2021-08-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210812_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='session',
        ),
    ]
