# Generated by Django 3.2.5 on 2021-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attendant_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
