# Generated by Django 3.2.5 on 2021-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210813_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
