# Generated by Django 3.2.5 on 2022-01-31 16:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='coach_cover')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover_image')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile_image'),
            preserve_default=False,
        ),
    ]
