# Generated by Django 3.2.5 on 2022-01-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220131_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AddField(
            model_name='session',
            name='coaches',
            field=models.ManyToManyField(to='core.Coach'),
        ),
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MainSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='mainsession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mainsession'),
            preserve_default=False,
        ),
    ]
