# Generated by Django 3.2.5 on 2022-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220222_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
