# Generated by Django 3.2.5 on 2022-02-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tribe_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='color',
        ),
    ]
