# Generated by Django 3.2.5 on 2022-02-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tribe_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='man',
            field=models.BooleanField(default=False),
        ),
    ]
