# Generated by Django 3.2.5 on 2022-02-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_intern_colorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='colorname',
        ),
    ]
