# Generated by Django 3.2.5 on 2021-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendants',
            field=models.ManyToManyField(blank=True, to='core.Attendant'),
        ),
    ]
