# Generated by Django 3.2.5 on 2021-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210812_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
