# Generated by Django 3.2.5 on 2021-08-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
    ]
