# Generated by Django 3.2.5 on 2021-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_intern_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
