# Generated by Django 3.2.5 on 2022-01-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220131_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='group',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='tribe',
        ),
    ]
