# Generated by Django 3.2.5 on 2022-02-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220131_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mainsession',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
