# Generated by Django 3.2.5 on 2022-02-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220222_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='tribe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tribe'),
            preserve_default=False,
        ),
    ]
