# Generated by Django 3.2.5 on 2022-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_session_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
