# Generated by Django 3.2.5 on 2022-02-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_intern_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='man',
        ),
    ]
